apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: delivery-prod-pipeline
description: "CI/CD pipeline for Cloud Run"

serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
      strategy:
        standard:
          verify: false  # Automatically deploys to Dev without approval
    - targetId: prod
      profiles: [prod]
      strategy:
        standard:
          verify: true # Requires approval to deploy to Prod

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: "Development Environment"
run:
  location: us-central1

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: "Production Environment"
run:
  location: us-central1
