steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    
    args: ['build', '-t', '<region>-docker.pkg.dev/$PROJECT_ID/training-repo/py-helloworld:$SHORT_SHA', '.']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '<region>-docker.pkg.dev/$PROJECT_ID/training-repo/py-helloworld:$SHORT_SHA']

  # Submit deployment to Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'
      - '--delivery-pipeline=delivery-prod-pipeline'
      - '--region=<region>'
      - '--images=my-app=<region>-docker.pkg.dev/$PROJECT_ID/training-repo/py-helloworld:$SHORT_SHA'
    secretEnv: ['REPO_URL']

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/REPO_URL/versions/latest"
      env: "REPO_URL"

substitutions:
  _SERVICE_NAME: "hello-world"
